### ISSUE TITLE
Error when starting strapi after configuring plugin

### ISSUE THREAD

**Issue by Noou-Ben** [redon2/strapi-plugin-refresh-token#2]
I am getting the below error

` Error: Error on attribute user in model token(plugin::refresh-token.token): inversedBy attribute refresh_tokens not found   ││   target plugin::users-permissions.user
at Metadata.loadModels (E:\YYY\XXX\ZZZ\node_modules\@strapi\database\dist\index.js:2740:19)
at Database.init (E:\YYY\XXX\ZZZ\node_modules\@strapi\database\dist\index.js:7063:19)
at Strapi.bootstrap (E:\YYY\XXX\ZZZ\node_modules\@strapi\core\dist\Strapi.js:341:19)
at Strapi.load (E:\YYY\XXX\ZZZ\node_modules\@strapi\core\dist\Strapi.js:318:16)
at async Module.develop (E:\YYY\XXX\ZZZ\node_modules\@strapi\strapi\dist\node\develop.js:148:28)
at async action (E:\YYY\XXX\ZZZ\node_modules\@strapi\strapi\dist\cli\commands\develop.js:18:5)
at async Command.parseAsync (E:\YYY\XXX\ZZZ\node_modules\commander\lib\command.js:923:5)
at async runCLI (E:\YYY\XXX\ZZZ\node_modules\@strapi\strapi\dist\cli\index.js:75:3)   `

**Comment by redondi88** [comment]
You missed a part of the config. you need to add extend the user schema

**Comment by Noou-Ben** [comment]
@redondi88 

I did do this, maybe wrongly though?

https://pastebin.com/nSNNuFxR

![image](https://github.com/user-attachments/assets/0df65ff4-4852-4c50-8c06-7a32fa08e24a)

Please could you offer some guidance? thank you

**Comment by redondi88** [comment]
You need to add that inside attributes :)

**Comment by Noou-Ben** [comment]
Ah that was a silly mistake on my part. Thank you for the awesome support! :)
